### ISSUE TITLE
Building project

### ISSUE THREAD

**Issue by Skyguysnips** [3ventic/BotVentic#8]
Building a project doesn't work as it continuously states that the type ThreadSafeList<EmoteInfo> could not be found, TwitchbotCommons could not be found and ThreadSafeList<BotVentic.EmoteInfo> does not contain a public definition for GetEnumerator

**Comment by 3ventic** [comment]
Sorry about this. I added a dependency from ohbot, my Twitch chat bot project, without realizing other people of course don't have it.

I've added a download link to the DLL in the readme, but you can also replace all references to `ThreadSafeList` with a normal `List` to avoid having to use it. It'll likely need locks to avoid oddities from happening if emotes are used while they're being reacquired from the APIs.
